name: trubrics

dependencies:
  - python=3.11
  - pip
  - pip:
    - ipython
    - ipykernel
    - jupyter
    - scikit-learn
    - matplotlib
    - plotly
    - trubrics[streamlit]
    - black[jupyter]
